#!/usr/bin/env bash

which autoselect > /dev/null 2>&1
if test $? -ne 0; then
    echo "Run 'cargo install --release' to install the program"
    exit 1
fi

OUTPUT=$(autoselect)
if test $? -ne 0; then
    exit 1
fi

if test -e "new.txt"; then
    mv "new.txt" "old.txt"
else
    echo "" >> "old.txt"
fi
echo "$OUTPUT" >> "new.txt"

if ! cmp -s "old.txt" "new.txt"; then
    nvim -d "old.txt" "new.txt"
fi

